# Default values for spark.
# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.
# name: value

Spark:
  Path: "/opt/spark"

Master:
  Name: master
  Image: "cloudpg/spark"
  ImageTag: "master-2.4.3"
  Replicas: 1
  Component: "spark-master"
  Cpu: "100m"
  Memory: "1024Mi"
  ServicePort: 7077
  ContainerPort: 7077
  # Set Master JVM memory. Default 1g
  # DaemonMemory: 1g
  ServiceType: ClusterIP

WebUi:
  Name: webui
  ServicePort: 8080
  ContainerPort: 8080

